name: Sync_Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */1 * * *"

jobs:
  notion-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Convert Notion to Markdown
        uses: Doradx/notion2markdown-action@latest
        with:
          notion_secret: ${{ secrets.NOTION_TOKEN }}
          database_id: ${{ secrets.NOTION_DATABASE_ID }}
          migrate_image: true
          picBedConfig: ${{ secrets.PICBED_CONFIG }}
          page_output_dir: "content"
          post_output_dir: "content/posts/notion"
          clean_unpublished_post: false

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync from Notion"
